In [24]:
import pandas as pd

In [68]:
file_path = "data/data.csv"
df = pd.read_csv(file_path, index_col= "id")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5110 entries, 9046 to 44679
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             5110 non-null   object
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64
 3   heart_disease      5110 non-null   int64
 4   ever_married       5110 non-null   object
 5   work_type          5110 non-null   object
 6   Residence_type     5110 non-null   object
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     5110 non-null   object
 10  stroke             5110 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 479.1+ KB

In [81]:
featuers = df.columns.to_list()[0: -1]
df[featuers].values[0]

array(['Male', 67.0, 0, 1, 'Yes', 'Private', 'Urban', 228.69, 36.6,
       'formerly smoked'], dtype=object)

In [62]:
average_bmi = round(df["bmi"].mean(), 1)

round(average_bmi, 1)

df["bmi"] = df["bmi"].fillna(average_bmi)

        # String yazıları label'la 
df["smoking_status"] = df["smoking_status"].replace(["never smoked" , "Unknown", "formerly smoked", "smokes"], [0, 1, 2, 3])

        # Gender'ları label'la 
df["gender"] = df["gender"].replace(["Male", "Female"], [0, 1])

        # Evlenip Evlenmediklerini Label'la 
df["ever_married"] = df["ever_married"].replace(["No", "Yes"], (0, 1))

        # İş tiplerini label'la 
df["work_type"] = df["work_type"].replace(["Private", "Self-employed", "children", "Govt_job", "Never_worked"])

        # Residence_Type'ı Label'la 
df["Residence_type"] = df["Residence_type"].replace(["Urban", "Rural"], [0, 1])

/var/folders/hf/kdtlw_gj1qd7yh6kbwj63n640000gn/T/ipykernel_52113/11153119.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["smoking_status"] = df["smoking_status"].replace(["never smoked" , "Unknown", "formerly smoked", "smokes"], [0, 1, 2, 3])
/var/folders/hf/kdtlw_gj1qd7yh6kbwj63n640000gn/T/ipykernel_52113/11153119.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["ever_married"] = df["ever_married"].replace(["No", "Yes"], (0, 1))
/var/folders/hf/kdtlw_gj1qd7yh6kbwj63n640000gn/T/ipykernel_52113/11153119.py:17: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df["work_type"] = df["work_type"].replace(["Private", "Self-employed", "children", "Govt_job", "Never_worked"])
/var/folders/hf/kdtlw_gj1qd7yh6kbwj63n640000gn/T/ipykernel_52113/11153119.py:20: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Residence_type"] = df["Residence_type"].replace(["Urban", "Rural"], [0, 1])

In [63]:
df.work_type.value_counts()

work_type
Private    5110
Name: count, dtype: int64

### BMI'da eksiklik var.

np.float64(28.9)

In [50]:
df["bmi"].fillna(average_bmi, inplace= True)
df

/var/folders/hf/kdtlw_gj1qd7yh6kbwj63n640000gn/T/ipykernel_52113/3160073175.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["bmi"].fillna(average_bmi, inplace= True)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
id,,,,,,,,,,,
9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.9,never smoked,1
31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
18234,Female,80.0,1,0,Yes,Private,Urban,83.75,28.9,never smoked,0
44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [60]:
df["Residence_type"].value_counts()

Residence_type
Urban    2596
Rural    2514
Name: count, dtype: int64

In [57]:
df["smoking_status"] =df["smoking_status"].replace(["never smoked", "Unknown", "formerly smoked", "smokes"], [1, 0, 2, 3])
df.smoking_status.value_counts()

/var/folders/hf/kdtlw_gj1qd7yh6kbwj63n640000gn/T/ipykernel_52113/3424717148.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["smoking_status"] =df["smoking_status"].replace(["never smoked", "Unknown", "formerly smoked", "smokes"], [1, 0, 2, 3])

smoking_status
1    1892
0    1544
2     885
3     789
Name: count, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(df, train_size= 0.7, random_state= 42)

In [12]:
train_df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
id,,,,,,,,,,,
24257,Male,4.00,0,0,No,children,Rural,90.42,16.2,Unknown,0
56179,Male,29.00,0,0,No,Private,Urban,207.58,22.8,smokes,0
36388,Male,44.00,1,0,Yes,Private,Rural,91.28,26.5,never smoked,0
59405,Female,68.00,1,0,Yes,Private,Urban,150.74,40.3,Unknown,0
46643,Female,62.00,0,0,Yes,Private,Rural,82.57,36.0,formerly smoked,0
...,...,...,...,...,...,...,...,...,...,...,...
13846,Male,43.00,0,0,Yes,Govt_job,Rural,88.00,30.6,never smoked,0
1307,Female,61.00,1,0,Yes,Private,Rural,170.05,60.2,smokes,0
31481,Female,1.16,0,0,No,children,Urban,97.28,17.8,Unknown,0
61827,Male,80.00,0,0,Yes,Self-employed,Rural,196.08,31.0,formerly smoked,0
28933,Female,46.00,0,0,Yes,Private,Rural,100.15,50.3,smokes,0